#app secret for twitter
FACEBOOK_APP_ID: 1133935950027496
FACEBOOK_APP_SECRET: 4864dafba5b075181c26f0697661a7dc

#App secret for twitter
TWITTER_APP_ID: '3fEMdi0x0JYHCvepin7ZLc8pd'
TWITTER_APP_SECRET: '41dq2b2TcWE8WvzlQnMrH36WNATNZvJiGbXKmV6hL4JZtsN7dC'
